name: Run Daily Robot
on:
  schedule:
    - cron: '0 0 * * *' # S'exécute à minuit UTC tous les jours
jobs:
  run-robot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pandas supabase # ajoute tes dépendances ici
      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python cron_robot.py
